name: Pull Request Cheker
on:
  pull_request:
    branches:
      - master
  check_run:
    types: [created, rerequested, requested_action]

jobs:
  testing:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install setuptools wheel twine
      - name: Checks
        run: |
          python -m unittest discover -s tests -v

