name: Release Creation

# WARNING !!!
# Please set variable API_URL in your secrets at project settings. It making the build file universal
#

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-devel.txt
          python -m pip install -r requirements.txt

      - name: Setting variables part 1
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build wheel
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          python setup.py bdist_wheel --update-link="${API_URL}" --version="${SOURCE_TAG}"

      - name: Create Release
        uses: actions/github-script@v3
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs').promises;
            const { repo: { owner, repo }, sha } = context;

            const release = await github.repos.createRelease({
              owner, repo,
              tag_name: process.env.SOURCE_TAG,
              draft: false,
              target_commitish: sha,
              name: 'OpenStack-CLI ' + process.env.SOURCE_TAG
            });

            for (let file of await fs.readdir('./dist')) {
              console.log('Uploading -> ', file);

              await github.repos.uploadReleaseAsset({
                owner, repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(`./dist/${file}`)
              });
            }
